-- Uptech Consulting admin dashboard — Auto-adjust Onboarding Case Numbers on Delete
-- Run this once in the Supabase SQL editor.
--
-- Changes case_number from GENERATED ALWAYS to GENERATED BY DEFAULT so it can be updated.
-- Creates an automatic trigger that shifts down all higher case numbers when any record is deleted,
-- closing gaps immediately.
-- Resets the identity sequence so new submissions continue from max(case_number) + 1.

-- 1. Allow updates to case_number
alter table public.onboarding_submissions
  alter column case_number set generated by default;

-- 2. Function to adjust case numbers on delete and update sequence
create or replace function public.adjust_onboarding_case_numbers()
returns trigger as $$
declare
  seq_name text;
  max_num integer;
begin
  -- Decrement all case numbers greater than the deleted record's case_number
  update public.onboarding_submissions
  set case_number = case_number - 1
  where case_number > old.case_number;

  -- Reset sequence to current max case_number so the next submission gets max + 1
  select pg_get_serial_sequence('public.onboarding_submissions', 'case_number') into seq_name;
  if seq_name is not null then
    select coalesce(max(case_number), 127) into max_num from public.onboarding_submissions;
    perform setval(seq_name, max_num);
  end if;

  return old;
end;
$$ language plpgsql security definer;

-- 3. Trigger on DELETE
drop trigger if exists onboarding_adjust_case_numbers_on_delete on public.onboarding_submissions;
create trigger onboarding_adjust_case_numbers_on_delete
  after delete on public.onboarding_submissions
  for each row
  execute function public.adjust_onboarding_case_numbers();

-- 4. Utility function to close any existing gaps and renumber sequentially
create or replace function public.resequence_all_onboarding_cases()
returns void as $$
declare
  seq_name text;
  min_num integer;
  curr_num integer;
  r record;
begin
  select min(case_number) into min_num from public.onboarding_submissions;
  if min_num is null then
    return;
  end if;

  curr_num := min_num;
  for r in (
    select id from public.onboarding_submissions
    order by submitted_at asc, created_at asc, case_number asc
  ) loop
    update public.onboarding_submissions
    set case_number = curr_num
    where id = r.id and case_number != curr_num;
    curr_num := curr_num + 1;
  end loop;

  select pg_get_serial_sequence('public.onboarding_submissions', 'case_number') into seq_name;
  if seq_name is not null then
    perform setval(seq_name, curr_num - 1);
  end if;
end;
$$ language plpgsql security definer;

grant execute on function public.resequence_all_onboarding_cases() to authenticated;

-- 5. Immediately close any existing gaps in current data (e.g. #152, #154, #155 -> #152, #153, #154)
select public.resequence_all_onboarding_cases();
