// AUTO-GENERATED by scripts/prep-real-images.mjs — do not edit by hand.
// Source photos are the real Uptech Consulting team/office photographs in
// public/images/real-image*.jpg, converted to WebP here. Each entry carries
// its intrinsic size so next/image can reserve layout space, and a 12px
// LQIP for slow connections.

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
};

export const images = {
  "ops-center": {
    src: "/images/ops-center.webp",
    width: 2048,
    height: 1366,
    alt: "The Uptech Consulting team reviewing a client engagement together",
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoMAAgAAwBSJYwCdAYp5yA39m/RAADOOAbBofP/oULu0h7oTjMgE6rN8VHcsKlZAp48itrPxbKLoJtOKmMgwP9En39MLF3BigAAAA==",
  },
  "dedicated-advisor": {
    src: "/images/dedicated-advisor.webp",
    width: 1440,
    height: 960,
    alt: "A specialist and colleagues reviewing a client case together",
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMAAgAAwBSJaACdAEDe7zrpoAA/oY6fzELYa83w7rO6hnhfe4LN3wMmXIPn5JKNlcKyINTg9FD1g1bpNJExDeD3ioJsS1+6/NQAAAA",
  },
  "career-review": {
    src: "/images/career-review.webp",
    width: 1440,
    height: 960,
    alt: "The Uptech Consulting team walking through a candidate profile together",
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoMAAgAAwBSJZQCw7ELKVU7wAD+4lX6G9UVSEGRR2Ng+ahb0CPtck37+ViE/kFanaj0Qa8ObB03so3Om9JBuoDoxYG4yT3gdpDHQAAA",
  },
  "compliance-advisory": {
    src: "/images/compliance-advisory.webp",
    width: 1440,
    height: 960,
    alt: "Uptech Consulting advisers reviewing compliance documents in a meeting room",
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoMAAgAAwBSJQBOgMWWs3B0bAD+ic5Ygc2c3DCEmIg0pe742Iwqc82g6q3yASDg27kvr/Kj+QO35z1x9mMVDMV4yAbs0d+vFAAAAA==",
  },
  "it-advisory": {
    src: "/images/it-advisory.webp",
    width: 1440,
    height: 960,
    alt: "The Uptech Consulting team working together at a boardroom table",
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoMAAgAAwBSJagCdMn8IFgnNBHaYAD+64/2EChBgvhofM0ce/46MprLUeBICVeXxKU35XZ3223vWmzL8haetS2tAhrFK1e89gEFoymBAAA=",
  },
  "cross-border-boardroom": {
    src: "/images/cross-border-boardroom.webp",
    width: 2048,
    height: 1366,
    alt: "The Uptech Consulting team reviewing a formalisation case together",
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAgAAwBSJQBOgCK1z75hJgAA9ijxUqRkaiAWEmyroMOXcJ3pCf1Ictz028dXPo5OHsVQooFWzgAno80gKryBfv+AAA==",
  },
  "infrastructure-corridor": {
    src: "/images/infrastructure-corridor.webp",
    width: 1440,
    height: 960,
    alt: "The Uptech Consulting team collaborating in the office",
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAgAAwBSJZQAD4wQybqwS0AA9dAaVcDFiO5DXWcE0XMF6k+JxWUwsii8nnJcw4L7ccHIzhjkIHYB4AA=",
  },
  "team-lineup": {
    src: "/images/team-lineup.webp",
    width: 1440,
    height: 960,
    alt: "The Uptech Consulting team",
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMAAgAAwBSJQBOgCHheHzQAAD5NfudGL7tPXJJrj7DzxXGoSBhomW6r1viAqOUiONz5EfZc+N+lE57aXtuH73uAAA=",
  },
  "team-lounge": {
    src: "/images/team-lounge.webp",
    width: 1440,
    height: 960,
    alt: "The Uptech Consulting team in conversation",
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAgAAwBSJYwC7AEKVkWMbpAA/I/OdPJAyqPdbBo8yJ0lfnUYZ0/zlDXPSKfNSovQNw1sZcIix1rl82Eo1EDeLcoIAA==",
  },
  "team-presenting": {
    src: "/images/team-presenting.webp",
    width: 2048,
    height: 1368,
    alt: "An Uptech Consulting specialist presenting to colleagues",
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMAAgAAwBSJQBOgCH6l1iBwAAA/DUno74CWWvvdF56jj3LqTJr7DumMlf8gbTyH6rG9GnnfH+bs9GTQlRs5lGIJYsUAAAA",
  },
} satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof images;
