// AUTO-GENERATED by scripts/prep-images.mjs — do not edit by hand.
// Source renders live in stitch_uptech_consulting_homepage_redesign/ and are
// cropped + re-encoded to WebP here. Each entry carries its intrinsic size so
// next/image can reserve layout space, and a 12px LQIP for slow connections.

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
};

export const images = {
  "ops-center": {
    src: "/images/ops-center.webp",
    width: 1376,
    height: 768,
    alt: "Operations centre analyst monitoring infrastructure dashboards",
    blurDataURL:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAcAAwBSJQBOgB9DtA5EAAD+7sczefcoIT7iaWxuDzdC/rKAJFlPj3nqyNRzgjNqAAAA",
  },
  "dedicated-advisor": {
    src: "/images/dedicated-advisor.webp",
    width: 696,
    height: 768,
    alt: "A career account specialist reviewing an application at her desk",
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoMAA0AAwBSJYwC7AEsK2o2gAD8PyMn81jILcGG9MpQCCrqHPnXyq3zlu8iSDf0QfIfBzm6i9RMjVMz7pKK1JJPzx6zWeUErkAg+YbNScF4ycJWKFhJxbUVmuAAAA==",
  },
  "career-review": {
    src: "/images/career-review.webp",
    width: 1120,
    height: 768,
    alt: "An adviser walking a client through their profile in a meeting room",
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAgAAwBSJQBOgB6VvCNv9AAA/toBH6cQx9EcBj389YTga6Pge4ZS5YgQlNPko1/bvAuRUFIi4exCAAA=",
  },
  "compliance-advisory": {
    src: "/images/compliance-advisory.webp",
    width: 1376,
    height: 768,
    alt: "Consultants reviewing tax compliance and audited financial files",
    blurDataURL:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAcAAwBSJZwAAu0deZE6QAD+6gAksDi4WXTpk3KolAVjjwG74nJyWW6JcgFNL5+AAAAA",
  },
  "it-advisory": {
    src: "/images/it-advisory.webp",
    width: 1200,
    height: 896,
    alt: "A team reviewing cloud architecture on a boardroom display",
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAAkAAwBSJYwCdAD7EnqIKQAA996ZnxKtJnb5+rWCni97LBV8FNNSz164V394FXg/qgSjN2U8hr+Hq5RQsgDS3hNdjq1ncEYAAA==",
  },
  "cross-border-boardroom": {
    src: "/images/cross-border-boardroom.webp",
    width: 1376,
    height: 768,
    alt: "Two advisers signing corporate formalisation documents at dusk",
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoMAAcAAwBSJQBOj+ADMqKZv4tAAP7dtimyNqZI1vc5RHgpwf6ysDW+fWrZ9Pc6p1/dYSs4Fub9t6UMCp9LYnD202unIzq1phj1QAAA",
  },
  "infrastructure-corridor": {
    src: "/images/infrastructure-corridor.webp",
    width: 1026,
    height: 768,
    alt: "A lit data centre corridor lined with server racks",
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoMAAkAAwBSJbACdADRT5bWgAD+5sEqPVAV1rsx8PcOhNs0ivKNDwVe6p5ArrTbAaH4R1lQUW/8bdLdIKid+R+dgxVBL3Afa0SgAA==",
  },
} satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof images;
