import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const ROOT = "C:/Users/Lil Legend/OneDrive/Desktop/Uptech-Website";
const SRC = path.join(ROOT, "stitch_uptech_consulting_homepage_redesign");
const OUT = path.join(ROOT, "public/images");

fs.mkdirSync(OUT, { recursive: true });

// `crop` removes AI-generated third-party brand artifacts baked into the
// source renders (an "ASCEND" logo, a "CAREER PATHWAYS" wall sign, a
// "CYBERNETIX GLOBAL" screen) which must not appear on UCO's site.
const jobs = [
  {
    out: "ops-center",
    src: "modern_dark_high_tech_enterprise_operations_center_with_dual_monitor",
    alt: "Operations centre analyst monitoring infrastructure dashboards",
  },
  {
    out: "dedicated-advisor",
    src: "a_warm_encouraging_scene_of_a_professional_career_advisor_or_account_specialist",
    crop: { left: 680, top: 0, width: 696, height: 768 },
    alt: "A career account specialist reviewing an application at her desk",
  },
  {
    out: "career-review",
    src: "a_warm_high_contrast_cinematic_wide_shot_of_a_modern_glass_executive_corporate",
    crop: { left: 0, top: 0, width: 1120, height: 768 },
    alt: "An adviser walking a client through their profile in a meeting room",
  },
  {
    out: "compliance-advisory",
    src: "a_high_end_cinematic_corporate_african_business_consulting_and_tax_compliance",
    alt: "Consultants reviewing tax compliance and audited financial files",
  },
  {
    out: "it-advisory",
    src: "corporate_it_consultant_and_systems_engineer_reviewing_technical_architecture",
    alt: "A team reviewing cloud architecture on a boardroom display",
  },
  {
    out: "cross-border-boardroom",
    src: "a_high_end_cinematic_corporate_legal_compliance_and_business_formalisation",
    alt: "Two advisers signing corporate formalisation documents at dusk",
  },
  {
    out: "infrastructure-corridor",
    src: "a_high_end_modern_server_room_corridor_and_cloud_datacenter_infrastructure_with",
    crop: { left: 350, top: 0, width: 1026, height: 768 },
    alt: "A lit data centre corridor lined with server racks",
  },
];

const manifest = [];

for (const job of jobs) {
  const input = path.join(SRC, job.src, "screen.png");
  let pipeline = sharp(input);
  if (job.crop) pipeline = pipeline.extract(job.crop);

  const buf = await pipeline.webp({ quality: 80, effort: 6 }).toBuffer();
  const meta = await sharp(buf).metadata();
  const outFile = path.join(OUT, `${job.out}.webp`);
  fs.writeFileSync(outFile, buf);

  // 12px-wide LQIP so slow connections paint something immediately.
  const blur = await sharp(buf).resize(12).webp({ quality: 45 }).toBuffer();

  manifest.push({
    key: job.out,
    src: `/images/${job.out}.webp`,
    width: meta.width,
    height: meta.height,
    alt: job.alt,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
  });

  console.log(
    `${job.out}.webp  ${meta.width}x${meta.height}  ${(buf.length / 1024).toFixed(0)}KB  (blur ${blur.length}B)`,
  );
}

const ts = `// AUTO-GENERATED by scripts/prep-images.mjs — do not edit by hand.
// Source renders live in stitch_uptech_consulting_homepage_redesign/ and are
// cropped + re-encoded to WebP here. Each entry carries its intrinsic size so
// next/image can reserve layout space, and a 12px LQIP for slow connections.

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
};

export const images = {
${manifest
  .map(
    (m) => `  "${m.key}": {
    src: "${m.src}",
    width: ${m.width},
    height: ${m.height},
    alt: "${m.alt.replace(/"/g, '\\"')}",
    blurDataURL:
      "${m.blurDataURL}",
  },`,
  )
  .join("\n")}
} satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof images;
`;

fs.mkdirSync(path.join(ROOT, "lib"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "lib/images.ts"), ts);
console.log("\nWrote lib/images.ts");
